@partner_api_key = PARTNER_API_KEY
@referral_customer_api_key = REFERRAL_CUSTOMER_API_KEY
@API_KEY = EASYPOST_API_KEY

# Get EasyPost public key for authenticating with Stripe
GET https://api.easypost.com/v2/partners/stripe_public_key
Authorization: Bearer {{partner_api_key}}
Content-Type: application/json

###

# Add a Stripe credit card to referral customer's account
POST https://api.easypost.com/v2/credit_cards
Authorization: Bearer {{referral_customer_api_key}}
Content-Type: application/json

{
  "credit_card": {
    "stripe_object_id": "tok_...",
    "priority": "primary"
  }
}

###

# List account payment methods
GET https://api.easypost.com/v2/payment_methods
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

###

# Fund account with on-file credit card ($10.00)
POST https://api.easypost.com/v2/credit_cards/{{CREDIT_CARD_ID}}/charges
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

{
  "amount": 1000
}

###

# Fund account with on-file bank account ($10.00)
POST https://api.easypost.com/v2/bank_accounts/{{BANK_ACCOUNT_ID}}/charges
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

###

# Delete an on-file credit card from account
DELETE https://api.easypost.com/v2/credit_cards/{{CREDIT_CARD_ID}}
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

###

# Delete an on-file bank account from account
DELETE https://api.easypost.com/v2/bank_accounts/{{BANK_ACCOUNT_ID}}
Authorization: Bearer {{API_KEY}}
Content-Type: application/json
