@API_KEY = EASYPOST_API_KEY

# Create a customs item
POST https://api.easypost.com/v2/customs_items
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

{
  "customs_item": {
    "description": "T-shirt",
    "quantity": "1",
    "weight": "5",
    "value": "10",
    "hs_tariff_number": "123456",
    "origin_country": "US"
  }
}

###

# Retrieve a customs item
GET https://api.easypost.com/v2/customs_items/{{CUSTOMS_ITEM_ID}}
Authorization: Bearer {{API_KEY}}
Content-Type: application/json
