@API_KEY = EASYPOST_API_KEY

# Create a Refund
POST https://api.easypost.com/v2/refunds
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

{
  "refund": {
    "carrier": "USPS",
    "tracking_codes": [
      "EZ1000000001"
    ]
  }
}

###

# Retrieve a Refund
GET https://api.easypost.com/v2/refunds/{{REFUND_ID}}
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

###

# List all Refunds
GET https://api.easypost.com/v2/refunds
    ?page_size=10
Authorization: Bearer {{API_KEY}}
Content-Type: application/json
