inherit_from: easycop.yml

# We ignore frozen string literal comments to simplify the sample code snippets
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/VariableNumber:
  Exclude:
    - 'official/docs/ruby/**/options/create-with-options.rb'
Lint/UselessAssignment:
  Exclude:
    - 'official/docs/ruby/**/users/retrieve.rb'
    - 'official/docs/ruby/**/api-keys/retrieve.rb'
Naming/FileName:
  Enabled: false

AllCops:
  SuggestExtensions: false
  Exclude:
    - bin/**/*
    - docs/**/*
    - examples/**/*
    - vendor/bundle/**/*
# We are ignoring RSpec/FilePath because Simplecov doesn't play nice with nested spec files
RSpec/FilePath:
  Enabled: false
# TODO: Remove this once we start using keyword arguments
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/easypost/services/*.rb'
