inherit_from: easycop.yml

# We ignore frozen string literal comments to simplify the sample code snippets
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/VariableNumber:
  Exclude:
    - 'official/docs/ruby/current/options/create-with-options.rb'
Lint/UselessAssignment:
  Exclude:
    - 'official/docs/ruby/current/users/retrieve.rb'
Naming/FileName:
  Enabled: false
