issues:
  exclude:
    - "other declaration of main"
    - "`main` redeclared in this block"
    - "`main` is unused"
    - "github.com/EasyPost/easypost-go"
    - "undeclared name: `easypost`"
    - "expected 'package'"


linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1019'
