issues:
  exclude:
    - "is unused"
    - "github.com/EasyPost/easypost-go"
    - "undeclared name: `easypost`"
    - "expected 'package'"


linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1019'
