EASYPOST_API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXX'

TWILIO_ACCOUNT_SID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
TWILIO_AUTH_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
SMS_TO_NUMBER = '1123456789'
SMS_FROM_NUMBER = '+1123456789'
